### ISSUE TITLE
Should all unbalanced Unbalanced programs do something?

### ISSUE THREAD

**Issue by CatsAreFluffy** [Wheatwizard/Unbalanced#1]
Currently programs like `()}` and `[]{()` do nothing, even though they're unbalanced. Why?

**Comment by Wheatwizard** [comment]
It would be nice if it were possible to prevent all unbalanced programs from doing nothing, but without doing anything cheap I believe this will be computationally impossible.  In order to prevent this you would need to make it so that every program has exactly one inverse, which can be reduced to the halting problem.  Ideally it would be the case but in reality this is impossible.
